source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'

target 'ZFPlayer_Example' do
    #pod 'KTVHTTPCache', :git => 'https://github.com/ChangbaDevs/KTVHTTPCache.git'
    pod 'ZFPlayer', :path => '../'

end
