use_frameworks!

target 'ZFPlayer_Example' do
  pod 'ZFPlayer', :path => '../'
  pod 'KTVHTTPCache', :git => 'https://github.com/ChangbaDevs/KTVHTTPCache.git'
  target 'ZFPlayer_Tests' do
    inherit! :search_paths

  end
end
