use_frameworks!

target 'ZFPlayer_Example' do
    pod 'KTVHTTPCache', :git => 'https://github.com/ChangbaDevs/KTVHTTPCache.git'
#    pod 'KSYMediaPlayer_iOS'
    pod 'ZFPlayer', :path => '../'
  target 'ZFPlayer_Tests' do
    inherit! :search_paths

  end
end
